export interface Product{
    id:number;
    subCategoryId:number;
    name:string;
    picture:string;
    picture1:string;
    picture2:string;
    picture3:string;
    øD:string;
    ødmax:string;
    ød1:string;
    ød2:string;
    l:string;
    l1:string;
    i1:string;
    i2:string;
    v:string;
    r:string;
    h1:string;
    b:string;
    k:string;
}